### ISSUE TITLE
Trouble with stack-chain module

### ISSUE THREAD

**Issue by raine** [medikoo/error-create#1]
Hey,

I'm having trouble using https://github.com/AndreasMadsen/stack-chain in a project with Error objects that are created using this module.

This is the error I'm getting:

```
TypeError: Cannot define property:callSite, object is not extensible.
    at Function.defineProperty (native)
    at ValidationError.Object.defineProperty.set (node_modules/stack-chain/stack-chain.js:177:12)
    at Function.prepareStackTrace (node_modules/stack-chain/stack-chain.js:123:20)
```

So I'm thinking it might be something in the way `error-create` builds the Error objects?

Any ideas appreciated!

**Comment by medikoo** [comment]
@raine thanks for report, still I think it may not be related to this module. At least there's nothing done within logic of `error-create` that will make created error instances non-extensible.

It'll be great if you can narrow it down to some simple test case, then we'll be able to say something more.

I'm closing it now, but let's keep discussion open, if it would appear as indeed bug in `error-create` we'll reopen it.

**Comment by raine** [comment]
For what it's worth, I have a similar issue if I just require [`error-callsites`](https://www.npmjs.com/package/error-callsites) anywhere in the project (no `stack-chain`).

```
TypeError: Cannot define property:__error_callsites, object is not extensible.
    at Function.defineProperty (native)
    at Function.Error.prepareStackTrace (node_modules/error-callsites/index.js:7:10)
```

**Comment by medikoo** [comment]
@raine as I mentioned, best if you prepare smallest possible test case that reproduces that, and that proves it's related to `error-create` being involved, then we'll go from there
